### ISSUE TITLE
Big Sur Testing

### ISSUE THREAD

**Issue by citinof** [kcrawford/dockutil#103]
I have successfully used Dockutil to add apps and remove Contacts and Mail, but it will not remove Podcasts, TV, News, or Books. I have also tried to move these apps to different places on the dock and they do not move.

Any help would be great!

**Comment by citinof** [comment]
Sorry, this is with Big Sur.

**Comment by kcrawford** [comment]
If you are running it at or before login, make sure Apple has added those items to the Dock before trying to change/remove them.

**Comment by citinof** [comment]
I am writing to the dock plist in User Template, so I assume that it is before Apple adds them. Then I would need to run this as at login I assume.

**Comment by kcrawford** [comment]
Correct Apple runs a dock fix up at login
