### ISSUE TITLE
[Big Sur 11.4 issue only] --view grid --display folder --sort name --no-restart

### ISSUE THREAD

**Issue by j0nathanr0gers** [kcrawford/dockutil#106]
Any thoughts on why **Big Sur < 11.3.1** these 2 lines works fine:
`sudo -u $LoggedInUser /usr/local/bin/dockutil --add '/Applications' --view grid --display folder --sort name --no-restart $LoggedInUserHome`
`sudo -u $LoggedInUser /usr/local/bin/dockutil --add '~/Downloads' --view grid --display folder --allhomes --no-restart $LoggedInUserHome`

But in **Big Sur 11.4+**
- The above for the **'/Applications'** folder yields: `--view auto --display stack --sort name`
- The above for the **'~/Downloads'** folder yields: `--view auto --display stack --sort name`

Regardless, thank you for what you do!  ;)

**Comment by kcrawford** [comment]
I think this was just fixed. Try with latest file.
