### ISSUE TITLE
Bigsur add new items not working correctly

### ISSUE THREAD

**Issue by fedeiglesias** [kcrawford/dockutil#107]
Im triying to add new Apps to the Dock but i think the last version of Big Sur that i have installed have diferent structure in the plist file. Here is an example of calculator App node in com.apple.dock.plist:

![image](https://user-images.githubusercontent.com/21363793/126048334-99c548e9-f2f9-4fc5-9ecf-036c2d7d2ecb.png)

There is some plan to fix this for Bigsur ?

**Comment by homcenco** [comment]
@fedeiglesias  Have no problems with  installation on my macOS (version: 11.5.2). Here's my code of [auto setup bash](https://github.com/homcenco/setup/blob/main/dock/install.sh) and a [quick manual](https://github.com/homcenco/setup/blob/main/dock/). Hope it helps!

**Comment by kcrawford** [comment]
Some improvements were made in dockutil 3.  Please retest in dockutil 3.  Big Sur and Monterey are supported.
