### ISSUE TITLE
Python in macOS 12 Monterey

### ISSUE THREAD

**Issue by DrWebster** [kcrawford/dockutil#111]
We use Dockutil to set up a custom Dock arrangement for our Mac users, and in testing with Monterey we're now getting a dialog box warning that the program needs to be updated to work in future macOS versions. It seems to be related to the deprecation of Python 2.7 in macOS:

https://developer.apple.com/documentation/macos-release-notes/macos-12_0_1-release-notes/#Python

Unfortunately it doesn't seem possible to disable the warning message. Apple's guidance is, moving forward, to bundle Python into any apps that need it instead of relying on the system version.

**Comment by kcrawford** [comment]
I'm curious what app you are running dockutil from that is triggering the prompt.

Here is a workaround
https://grahamrpugh.com/2021/10/25/monterey-disable-python-2-deprecation-warnings.html

Or you can use this fork if you have python3 installed
https://github.com/erikng/dockutil/tree/py3

Apologies for not getting this updated yet

**Comment by DrWebster** [comment]
Thanks for passing along that link to Graham's blog, I should have known he'd have a workaround ;-) That should get me going for now.

I'm using DockBuilder (https://github.com/ryangball/DockBuilder) which leverages dockutil as a component.

**Comment by tgleero** [comment]
Hallo!
I have no problems with dockutil 2.0.5 at all in macOS 12.1 on a new Macbook Pro 16” M1.
It works like a charm as always.

**Comment by kcrawford** [comment]
I see python2 is removed in macOS 12.3
So I'll try to have a new version out ASAP

**Comment by kiepenflicker** [comment]
I wanted to confirm again that dockutil brings up a Python deprecation related message when executed via a Jamf script. Maybe the command below helps someone to identify apps causing a deprecation prompt.

Command:
log show | grep -i "pythonprompt: Showing"

Message:
pythonprompt: Showing alert to user because "JamfManagementService" needs to be updated. Reason: Python 2.7 has reached sunset, and the caller is running Python 2.7 with args: : /usr/local/vwg/bin/dockutil --add /Applications/Microsoft Edge.app --after Mission Control.

**Comment by rjtort** [comment]
> Can I use last version 2.0.5, remove first line (hashbang) and launch it using following shell script?
> 
> ```
> #!/bin/sh
> if [ "$(command -v python3)" ]; then
>   python3 ./dockutil.py
> else
>   python ./dockutil.py
> fi
> ```

If you do, you'll be presented with the following message

![CleanShot 2022-02-09 at 12 39 20](https://user-images.githubusercontent.com/20286516/153270229-a1ba1d2d-3881-46f6-8cc6-9b79c8ec49b3.png)

**Comment by kcrawford** [comment]
I expect a beta version that works on macOS 12.3 will be available within a few days.

**Comment by Trikster-Online** [comment]
> I expect a beta version that works on macOS 12.3 will be available within a few days.

It would be awesome if it came bundled with p3.

**Comment by kcrawford** [comment]
dockutil 3.0.0 beta
https://github.com/kcrawford/dockutil/releases
Sorry package is not signed yet

**Comment by kcrawford** [comment]
Closing this with the 3.0 release which no longer uses python and is standalone.
