### ISSUE TITLE
dockutil does not work on Monterey 12.3 (Beta)

### ISSUE THREAD

**Issue by cipineda** [kcrawford/dockutil#114]
Hello dockutil fails to run on 12.3 Beta macOS.
Apple has removed /usr/bin/python and replaced it with /us/bin/python3.
symbolic links can't be created as this is a SIP protected folder.

Will you be able to update to point to the python3 binary?

**Comment by kcrawford** [comment]
dockutil 3 does not use python at all. Beta is available for testing
