### ISSUE TITLE
dockutil 3.0.0-beta.1 dock doesn't restart as expected

### ISSUE THREAD

**Issue by built2order** [kcrawford/dockutil#115]
Thanks for allowing us to test the new beta. This single tool creates a great user experience across the 3,000+ devices of which I manage.

When executing the following command as root, the application is added to the dock, however the user's dock doesn't restart (which is the expected behaviour):
`dockutil --add "$APPLICATION_PATH" /Users/$CURRENT_USER`

Restarting the dock is the current behaviour using the python version 2.0.5. This behaviour is also documented in the help page for the executable:

`  --restart/--no-restart  Whether to restart the Dock to apply the changes. (default: true)`

**Comment by kcrawford** [comment]
Thanks for comments and for testing!

I think I know what the issue is and will try to get this fixed soon.

**Comment by kcrawford** [comment]
Thanks for your patience.  Please retest in beta 2.  It should be fixed.

**Comment by built2order** [comment]
This issue is resolved in recent versions.
