### ISSUE TITLE
Bad Item label after add to dock

### ISSUE THREAD

**Issue by ferben** [kcrawford/dockutil#120]
`mkdir -p "/Applications/Test Folder 10.0.102.0 Alpha"`
`./dockutil --add "/Applications/Test Folder 10.0.102.0 Alpha" --section others --position first --view grid --display folder --sort name`
Place mouse over new dock icon.
item's label should be "Test Folder 10.0.102.0 Alpha", but is unexpectedly "Test App 10.0.102".

Regression:
dockutil 2.0.5 work correctly.

**Comment by kcrawford** [comment]
Closing this after the merge.  Thanks again

**Comment by ferben** [comment]
You are welcome.
Thank **you** for amazing tool 👍
