### ISSUE TITLE
Check if Application exist before adding to the dock

### ISSUE THREAD

**Issue by mvdbent** [kcrawford/dockutil#121]
the specifying paths in macOS 10 Catalina or higher note that the path to default Apple Applications is /System/Applications trigger me to reports this.

If you look into your Application folder, you will see the TextEdit application, however if you want to add the TextEdit.app the path is /System/Applications/TextEdit.app not /Applications/TextEdit.app (like how you see this in the GUI) but if you run this command
`dockutil --add /Applications/TextEdit.app`
dockutil will add TextEdit with a Question mark in the dock. unfortunately, dockutil doesn't check if the application exists on the device. For solve this you can create a function that will check if the application exists before he will run the command.  

It would be a great feature if dockutil first check if the path is valid (is the app there) and if not just error out with message that application path is not valid.

**Comment by kcrawford** [comment]
This will be in 3.0.1 version.
If the item doesn't exist in /Applications but does exist in /System/Applications it will use the /System/Applications path. 

Thanks for the suggestion.
