### ISSUE TITLE
dockutil 3.0.0 build issue

### ISSUE THREAD

**Issue by chenrui333** [kcrawford/dockutil#122]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>build error</summary>

```
$ $ xcodebuild -arch arm64 -project dockutil.xcodeproj -scheme dockutil -configuration Release CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO SYMROOT=build
...
dockutil-3.0.0/dockutil/DockUtil.swift:10:8: error: no such module 'ArgumentParser'
import ArgumentParser
       ^
```

</details>

relates to Homebrew/homebrew-core#96391

**Comment by kcrawford** [comment]
Does the build.sh script work?  There is a dependency on the Swift Argument Parser Swift package.

**Comment by ferben** [comment]
Xcode should resolve dependency automatically.
It need Apple's Dev account?

**Comment by chenrui333** [comment]
👋  Is there anyway that we can get rid of apple dev account dependency? Also is there any way for me to build with `swift` rather than `xcodebuild`, I dont know how to pull in `Swift Argument Parser Swift` dependency.

**Comment by sashkab** [comment]
It seems that #131 implements swift package manager support, something I proposed here.

**Comment by kcrawford** [comment]
Yes 3.1.0 is using swift package manager.
