### ISSUE TITLE
Launch under sudo issue

### ISSUE THREAD

**Issue by ferben** [kcrawford/dockutil#124]
In 2.0 when I launch dockutil under sudo (part of installer [pkg] solution), change my (logged user) Dock with following command:
`sudo ./dockutil.py --add /Applications/Test.app --section others --position first`

In 3.0 I get following error message:
`sudo ./dockutil --add /Applications/Test.app --section others --position first`
`Error: /var/root/Library/Preferences/com.apple.dock.plist does not seem to be a home directory or a dock plist`

Workaround:
Wrote "**$HOME**" variable at the end of commandline.
`sudo ./dockutil --add /Applications/Test.app --section others --position first "$HOME"`

It is change in default behavior.
Please let me know if it is permanent change or you are able to fix it.

Thank you

**Comment by kcrawford** [comment]
Thanks for reporting. This will be fixed in 3.0.1.

**Comment by ferben** [comment]
Thank you.
