### ISSUE TITLE
Not working on macOS 12.3 - need to upgrade Homebrew version from 2 to 3

### ISSUE THREAD

**Issue by Mellbourn** [kcrawford/dockutil#127]
Could you please update the [homebrew installation](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/dockutil.rb) so that it installs version 3 instead of 2?

Version 2 doesn't even work on standard macOS Monterey 12.3 anymore, since [python 2 has been removed](https://www.macrumors.com/2022/01/28/apple-removing-python-2-in-macos-12-3/#:~:text=Apple%20will%20no%20longer%20bundle,security%20patches%2C%20or%20other%20changes.). 

```
> dockutil
zsh: /opt/homebrew/bin/dockutil: bad interpreter: /usr/bin/python: no such file or directory
```

Thanks for a great tool!

**Comment by MarcoCBA** [comment]
I assume this will be installed as a "cask" package now, is that right?

**Comment by karnaker** [comment]
I get the same error, and would appreciate a fix. Doubling down on the thanks for making a great tool! ❤️

<img width="740" alt="Screen Shot 2022-03-23 at 4 09 03 PM" src="https://user-images.githubusercontent.com/35387991/159787027-d62ac6ca-e420-417f-82ba-c6f87fd69f4e.png">

**Comment by tuxpeople** [comment]
@Mellbourn and @karnaker that's actually the wrong place for this issue I think. As it is a `homebrew` issue and not a `dockutil` issue. That beeing said, I may bring some light into the darkness:

There was once a pull request on `homebrew-core` for this: https://github.com/Homebrew/homebrew-core/pull/96391. But it wouldn't build.

Fast forward, someone else opened a new PR for this: https://github.com/Homebrew/homebrew-core/pull/97394 There's a discussion in this PR about the build issue. As fas as I understood (I'm not a developer) situation is this: To be a formulae, the software must be able to be built from source. Which does not work for this software withe the current tools available in Homebrew. If this can not be fixed, the `dockutil` formulae must be removed and replaced by a cask. As casks can be binaries.

There's also already a corresponding issue over here: https://github.com/kcrawford/dockutil/issues/122. Still not being a developer, I understand from there that @sashkab has an idea for a solution for which he is awaiting a basic approval for this idea from @kcrawford prior to do all the work needed.

That being said, I see chances that eventually `dockutil` version 3.x will be available in Homebrew. 

Meanwhile, if you need to have it installed and want to do it in a automated manner, something like this would be possible:

```sh
brew install jq
DLURL=$(curl --silent "https://api.github.com/repos/kcrawford/dockutil/releases/latest" | jq -r .assets[].browser_download_url | grep pkg)
curl -sL ${DLURL} -o /tmp/dockutil.pkg
sudo installer -pkg "/tmp/dockutil.pkg" -target /
rm /tmp/dockutil.pkg
```

**Comment by shawndwells** [comment]
> Meanwhile, if you need to have it installed and want to do it in a automated manner, something like this would be possible:
> 
> ```shell
> brew install jq
> DLURL=$(curl --silent "https://api.github.com/repos/kcrawford/dockutil/releases/latest" | jq -r .assets[].browser_download_url | grep pkg)
> curl -sL ${DLURL} -o /tmp/dockutil.pkg
> sudo installer -pkg "/tmp/dockutil.pkg" -target /
> rm /tmp/dockutil.pkg
> ```


@tuxpeople thanks so much for posting this! Ran into this issue and your snippets worked great (clean install of macOS Monterey 12.3).

**Comment by lotyp** [comment]
I made temporary solution to get 3.0.2 version with brew:

```
$ brew tap lotyp/homebrew-formulae
$ brew install lotyp/formulae/dockutil
```

**Comment by brianephraim** [comment]
For zsh,  you need quotes here `... jq -r '.assets[].browser_download_url' ...`.
Becomes
```
brew install jq
DLURL=$(curl --silent "https://api.github.com/repos/kcrawford/dockutil/releases/latest" | jq -r '.assets[].browser_download_url' | grep pkg)
curl -sL ${DLURL} -o /tmp/dockutil.pkg
sudo installer -pkg "/tmp/dockutil.pkg" -target /
rm /tmp/dockutil.pkg
```

**Comment by hpedrorodrigues** [comment]
If anyone is willing to use a temporary solution, I've created a cask to use the new version [here](https://github.com/hpedrorodrigues/homebrew-tools/blob/master/Casks/dockutil.rb).

```sh
$ brew install --cask hpedrorodrigues/tools/dockutil
```

However, I'll deprecate it once an official cask is released.

**Comment by boldandbrad** [comment]
As happy as I am that there are a few community provided temporary solutions, this still needs to be fixed. Anyone actively working on this?

**Comment by ferben** [comment]
Hello,
AFAIK autor does not support Hombrew formula of dockutil.
If you want to add support you can do it on your own, please see https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by kcrawford** [comment]
With the 3.1.0 release, I think homebrew formula maintainers should have what they need now to update the formula.

**Comment by Mellbourn** [comment]
This is great! Just a piece of advice for others who may also be as confused as I was:

You should first uninstall the dockutil cask, explicitly:

```
brew uninstall --cask dockutil
```
then you can install the formula

```
brew install dockutil
```
If you do not uninstall the cask, _the cask may be found instead of the formula_ when running on the command line.
