### ISSUE TITLE
Dockutils does not work with MacOS Monterrey 12.3

### ISSUE THREAD

**Issue by smartinellimarco** [kcrawford/dockutil#129]
MacOS monterrey removed the python 2 binary at: /usr/bin/python
So calling dockutils produces:
zsh: /usr/local/bin/dockutil: bad interpreter: /usr/bin/python: no such file or directory

**Comment by smithki** [comment]
This issue is still valid, not sure why it has been closed.

**Comment by kcrawford** [comment]
dockutil version 3.x specifically addresses this. It does not use python.

**Comment by kcrawford** [comment]
I'm re-closing this issue.  If it is still an issue and you are using latest dockutil version, please explain.
