### ISSUE TITLE
Package fails to deploy / install via Intune/MDM

### ISSUE THREAD

**Issue by amagre** [kcrawford/dockutil#142]
The package version does not work when deployed by Intune. Fails with error "The app state is unknown (0x87D13B67)". This is likely because the package does not contain the _pkg-info_ file that needs to define the package version and CFBundleVersion strings. Please can this be fixed so that the package is deployable via MDM / Intune.

**Comment by kcrawford** [comment]
This seems like an Intune-specific issue.  I don't have experience with Intune.  Also, please try the latest version of dockutil as it is built as a signed notarized distribution package so I think any MDM should be able to deploy it.
