### ISSUE TITLE
Safari shows as an alias

### ISSUE THREAD

**Issue by shannonpasto** [kcrawford/dockutil#148]
Hi all.

When I add Safari to the dock using `dockutil -a "/Applications/Safari.app" -s apps` it shows the alias icon. No other app does this which I find really odd. Any ideas?

edit - I figure this is something to do with the hard linking that Apple do. I've tried all the locations I can find but still no luck

> /System/Library/Templates/Data/Applications/Safari.app
/System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app
/System/Volumes/Data/System/Library/Templates/Data/Applications/Safari.app
/System/Volumes/Data/Applications/Safari.app

Cheers,
Shannon

**Comment by mvught** [comment]
This is the path:
"/System/Cryptexes/App/System/Applications/Safari.app"

**Comment by shannonpasto** [comment]
Odd, I thought I tried that one.

Working now. Cheers

**Comment by mvught** [comment]
You can close this one 👍
