### ISSUE TITLE
request a new release

### ISSUE THREAD

**Issue by chenrui333** [kcrawford/dockutil#158]
👋 with the big change on the swift package manager support, it would be good to cut a new release. Thanks! 

cc @kcrawford

**Comment by chenrui333** [comment]
it would be also include [this license PR](https://github.com/kcrawford/dockutil/pull/157) for the new release as well. Thanks!

**Comment by chenrui333** [comment]
cc @kcrawford

**Comment by kcrawford** [comment]
3.1.0 released

**Comment by chenrui333** [comment]
shipped per https://github.com/Homebrew/homebrew-core/pull/158600
