### ISSUE TITLE
Any reason why is HomeBrew still pointing to  2.0.5.tar.gz from Sept 2016 when there is a latest dockutil 3.0.2 from Mar 2022?

### ISSUE THREAD

**Issue by hiavi** [kcrawford/dockutil#159]
Trying to install from dock util using **_homebrew is pulling in 2.0.5.tar.gz from Sept 2016_** with a message saying it is deprecated and users should lookout for alternatives, **_when in reality we have a more latest dockutil 3.0.2 from Mar 2022_**

Excerpt from homebrew (https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/d/dockutil.rb)

class Dockutil < Formula
  desc "Tool for managing dock items"
  homepage "https://github.com/kcrawford/dockutil"
  url "https://github.com/kcrawford/dockutil/archive/refs/tags/2.0.5.tar.gz"
  sha256 "6dbbc1467caaab977bf4c9f2d106ceadfedd954b6a4848c54c925aff81159a65"
  license "Apache-2.0"

**Comment by kcrawford** [comment]
Homebrew maintainers were waiting for conversion to swift package and license and release.  They should have what they need now.
