### ISSUE TITLE
Items are added but not always removed

### ISSUE THREAD

**Issue by acampbell86** [kcrawford/dockutil#28]
Sometimes when a user logs in, dockutil will add the programs that are called for, but it won't remove all the default dock items. There appears to be no discernible consistency, as I logged in as one user, and it worked famously but logged out and logged in as another user and it gave me everything.  The script I have running calls --remove all at the onset, so it should be removing all items.  And, it in fact, does work sometimes.  

Running in OS X 10.9.4, dockutil 2.0.0.

Any thoughts?

**Comment by aysiu** [comment]
Yeah, I'm having this issue as well, except I can't get the removes to work ever.

If I run the individual commands, they work. I've tried normal scripted remove commands and also with `--no-restart`. I've tried to `killall Dock` and to even put a `sleep 2` between the add commands and the remove commands or to switch up the order (both add items first and then remove, and remove items first and then add).

I love Dockutil for one-off changes, but I may have to deploy a premade Dock at least for a first run instead of using Dockutil with Outset to get a default Dock in there.

This is on El Capitan with the latest Dockutil version.

**Comment by erikng** [comment]
I can't say I've seen that issue. I used dockutil/outset upon every first login and I've not had an issue.

I do a remove-all and then add the items needed.

**Comment by aysiu** [comment]
> I do a remove-all and then add the items needed.
Ultimately, after a lot of experimentation, that was the only way I could get it to work—remove everything and then re-add from scratch. And, even then, I had to do a regular remove all (not a --no-restart).

The issue here is when you're just trying to take the default dock, remove some items from it and then add some items to it. The added items add fine. The removed items don't get removed at all. But if you run the individual commands (not scripted at login) to remove individual items, they remove just fine.

**Comment by kcrawford** [comment]
You may need to wait for the dock to set itself up before modifying it at login.  Especially at first login, the dock is setting itself up so your modifications might be happening at the same time.

I use a script that waits for the dock process then does its modifications.

Kyle

**Comment by aysiu** [comment]
Oh, I see—it's "removing" the items that don't exist yet because OS X is still generating the default Dock. Do you mind sharing your script that waits?

**Comment by magnusviri** [comment]
In older OS'es (10.6) /Library/Preferences/com.apple.dockfixup.plist controlled this behavior.  In newer OS'es (at least 10.9) this file is gone so I don't know where the functionality went.

**Comment by kcrawford** [comment]
I could add this to dockutil as an option.  But what would the option be called?

I'm thinking:

--wait-for-dock

Kyle

**Comment by erikng** [comment]
Perhaps instead of an option just add the logic itself. It shouldn't get in the way of current users with a dock that's already created.

**Comment by kcrawford** [comment]
Yeah good point.  I didn't want to affect people running it with no user logged in, but I could check for that.

Kyle

**Comment by kcrawford** [comment]
Actually the script I am using is doing a check for a default item (Messages) so I would need to test to find out if just checking for the dock to be running is sufficient.

This is what I'm using currently:

```
# Wait for a default dock
while ! /usr/local/bin/dockutil --list | grep Messages
do
    /bin/sleep 1
done
# actual dockutil dock modifications here
# /usr/local/bin/dockutil --add ...
```

**Comment by aysiu** [comment]
This doesn't make that much of a difference, but I've tested on El Capitan (may work on Yosemite any earlier, too—not sure), and fractions of seconds work, too, so

`/bin/sleep .25`

is a viable option in there. It won't load more than 3/4 of a second faster, of course...

**Comment by kcrawford** [comment]
There is a mod-count in the plist that increments to 2 on first login after the dock is setup by Apple. So that could be helpful for the first login scenario.

Kyle

**Comment by aysiu** [comment]
So something like this might work?

`#!/bin/bash

# Get current mod count
initialCount=$(defaults read com.apple.dock.plist mod-count)
currentCount=$(defaults read com.apple.dock.plist mod-count)
#echo -e "Initial count is $initialCount and current count is $currentCount\n"

# Prevent a potential infinite loop
counter=1

while [ "$initialCount" == "$currentCount" ] && [ "$counter" -lt 300 ]; do
   sleep .25
   currentCount=$(defaults read com.apple.dock.plist mod-count)
   #echo -e "Current count is now $currentCount\n"
   counter=$((counter + 1))
   #echo -e "Current counter is $counter\n"
done

## Make Dock changes with dockutil
/usr/local/bin/dockutil --remove 'BLAHBLAHBLAH'
`

**Comment by kcrawford** [comment]
Yes that's the idea.  Except I think we can specially check for Dock is running and mod-count == 1.

I don't know what happens during an upgrade though.  As something will likely run the fixup again to add Apple apps back in.

Changing the mod-count back to 1 doesn't seem to retrigger the fixup.

Would be nice to know what criteria triggers the apple apps getting added/re-added.

Kyle

**Comment by erikng** [comment]
Apple looks for the existence of /Library/Preferences/com.apple.dockfixup.plist.

It contains all the logic for what apps to add to docks. I personally use outset every-boot with a script that deletes this file.

**Comment by kcrawford** [comment]
~/Library or /Library?

Kyle

**Comment by erikng** [comment]
/Library

Date: Sat, 30 Apr 2016 08:59:02 -0700

**Comment by kcrawford** [comment]
Thanks.

I can't seem to trigger a fixup so I'm still missing something.

Kyle

**Comment by aysiu** [comment]
The only dockfixup I see in El Capitan is here (and protected by SIP):
/System/Library/CoreServices/Dock.app/Contents/Resources/com.apple.dockfixup.plist

I don't see one in /Library anywhere...

**Comment by erikng** [comment]
It only appears during specific updates. The last time it appeared was when Photos.app debuted.

**Comment by mvught** [comment]
`
#!/bin/bash

## This allows you to specify lists of items to remove and add in arrays, and then they'll be done in bulk using a for loop
## Items to remove should be the label (usually the name of the application)
## Items to add are the full path to the item to add (usually /Applications/NAMEOFAPP.app)
## A few examples are prepopulated in the arrays, but feel free to tweak as suits the needs of your organization

itemsToRemove=(
   "App Store"
   "System Preferences"
)

itemsToAdd=(
   "/Applications/TextWrangler.app"
   "/Applications/Firefox.app"
   "/Applications/Microsoft Word.app"
    "/Applications/Microsoft PowerPoint.app"
    "/Applications/Microsoft Outlook.app"
    "/Applications/Microsoft OneNote.app"
    "/Applications/Microsoft Excel.app"
    
)

for removalItem in "${itemsToRemove[@]}"
   do
      # Check that the item is actually in the Dock
      inDock=$(/usr/local/bin/dockutil --list | grep "$removalItem")
      if [ ! -z "$inDock" ]; then
         /usr/local/bin/dockutil --remove "$removalItem" --no-restart
      fi
   done


for additionItem in "${itemsToAdd[@]}"
   do
      # Check that the item is actually exists to be added to the Dock and that it isn't already in the Dock
      # Stripping path and extension code based on code from http://stackoverflow.com/a/2664746
      additionItemString=${additionItem##*/}
      additionItemBasename=${additionItemString%.*}
      inDock=$(/usr/local/bin/dockutil --list | grep "additionItemBasename")
      if [ -e "$additionItem" ] && [ -z "$inDock" ]; then
            /usr/local/bin/dockutil --add "$additionItem" --no-restart
      fi
   done

killall Dock

`

**Comment by aysiu** [comment]
> i have found something like this?

I wrote that. It isn't relevant here, though. That's just putting them in easy-to-read and easy-to-manage arrays. That doesn't account for waiting for the Dock to load before making changes.

**Comment by aysiu** [comment]
Looping back around. Is there any reason to favor waiting for the mod-count to go up from one over your original while loop? The original while loop seems to be effective.

**Comment by erikng** [comment]
Personally speaking I don't think so. Right now Apple isn't adding new applications to the dock, so we won't see a dockfixup anytime soon. Once a dockfixup comes back up, we can test it (but I still think simply removing it from /L/P will be sufficient).

**Comment by kcrawford** [comment]
Should I implement this so people don't have to write their own wait script for users logging in for the first time:

If we are modifying the dock of the currently logged in user and dock mod count is < ? then wait for up to X seconds for dock mod count to go up before attempting to modify the dock

Thoughts?

Kyle

**Comment by erikng** [comment]
I think that would definitely be ideal.

**Comment by aysiu** [comment]
Yes, if it can be done in dockutil itself, that'd be awesome. After all, even if it's not used in a login script, it would be used well after the first dock has been created.

**Comment by kcrawford** [comment]
I made the change in version 2.0.3.  If anyone can do some testing, that would be great.

**Comment by aysiu** [comment]
Awesome! I'll do some testing tomorrow, and then report back.

**Comment by aysiu** [comment]
I tested it once, and it seems good. I'll let you know if it shows any hiccups after further testing.

**Comment by erikng** [comment]
Tested and looks good.

**Comment by kcrawford** [comment]
Thanks for the testing @aysiu and @erikng.  I am closing this issue.
