### ISSUE TITLE
Unicode problem, can't remove item with an accent

### ISSUE THREAD

**Issue by NicolasDaigneault** [kcrawford/dockutil#29]
Hello, I have a problem to remove an item in the dock that the name is 'Mise à jour de logiciels'.  This is the french translation for the software Munki.

This is the command that I do and the result:

bash-3.2$ dockutil --remove 'Mise à jour de logiciels' --allhomes
/usr/local/bin/dockutil:605: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if dock_item['tile-data'].get('file-label') == item_name:
/usr/local/bin/dockutil:616: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if dock_item['tile-data'].get('file-label') == item_name:
item Mise à jour de logiciels was not found in /Users/pilier/Library/Preferences/com.apple.dock.plist

I tried the command with the version 1.4 and 2.0 of dockutil.  If I do the command dockutil --list, the item is showed like this:

Mise à jour de logiciels	/Applications/Utilities/Managed Software Update.app/	persistent-apps	/Users/pilier/Library/Preferences/com.apple.dock.plist

How can I remove it?  Thanks

**Comment by dkf2010** [comment]
Same problem here.
>$ dockutil --version
2.0.2

>$ dockutil --remove 'Geführte Softwareaktualisierung'
/usr/local/bin/dockutil:618: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if dock_item['tile-data'].get('file-label') == item_name:
item Geführte Softwareaktualisierung was not found in /Users/dkf/Library/Preferences/com.apple.dock.plist

**Comment by whitesiroi** [comment]
Same problem here.

dockutil --version
2.0.2

dockutil --remove 写真
/usr/local/bin/dockutil:618: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if dock_item['tile-data'].get('file-label') == item_name:
/usr/local/bin/dockutil:629: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if dock_item['tile-data'].get('file-label') == item_name:
item 写真 was not found in /Users/whitesiroi/Library/Preferences/com.apple.dock.plist

**Comment by kcrawford** [comment]
This should be fixed in 2.0.4

This worked for me.

dockutil --remove 'Héllo 😀'
