### ISSUE TITLE
Not working in Snow Leopard

### ISSUE THREAD

**Issue by phillymjs** [kcrawford/dockutil#30]
I reverted to 1.1.2 and it is working, but 2.0.0 appears to have a syntax error in the defaults command it sends. When I run it it returns the syntax guide you get if you just type "defaults" at a command prompt with no arguments.

**Comment by kcrawford** [comment]
Thanks for reporting the issue.  At this point I don't plan to fix dockutil 2.x to work on less than 10.9.
