### ISSUE TITLE
[FR] Add ability to add / remove / move spacers

### ISSUE THREAD

**Issue by leevigraham** [kcrawford/dockutil#31]
It would be great to add / remove / move spacer tiles.

http://css-tricks.com/snippets/html/add-spaces-to-dock-in-os-x/

**Comment by kcrawford** [comment]
Adding is implemented in master and will be part of the the next release.

`dockutil --add '' --type spacer --section apps --after Safari`

I'm not sure how to implement move and remove since spacers don't have a label.

I could implement remove all spacers.

**Comment by kcrawford** [comment]
Implemented removal of all spacer tiles in master

`dockutil --remove spacer-tiles`

If you need moving of spacer tiles, please open a new issue.  Thanks.
