### ISSUE TITLE
Can't import plist as Domain User

### ISSUE THREAD

**Issue by lgrimm** [kcrawford/dockutil#36]
Using a postinstall pkg script- dockutil is not installing an icon for the current logged in user:

The pkg succeeds but the log shows this error I get this on 10.8.5.

Dec 30 09:46:24 maccomp.global.domain.net.: ./postinstall: Sorry, user root is not allowed to execute '/usr/bin/defaults import /Users/grimml/Library/Preferences/com.apple.dock.plist /private/tmp/PKInstallSandbox.MXi7di/tmp/tmpKi7r0h' as grimml:LL\Domain Users on maccomp.global.domain.net.

Script:
# !/bin/bash
# Add My.app icons to existing users Dock

/usr/local/bin/dockutil --add '/Applications/Utilities/My.app' --allhomes

Sorry, user root is not allowed to execute '/usr/bin/defaults import /Users/grimml/Library/Preferences/com.apple.dock.plist /tmp/tmp4QBRZU' as grimml:LL\Domain Users on maccomp.global.domain.net.

Can you advise me on a solution?

Thanks very much

**Comment by kcrawford** [comment]
Closing this old inactive issue.  Please retest with latest dockutil and report back if you are still having the issue.
