### ISSUE TITLE
Super cool - thanks for this - is it possible to access non-persistent apps?

### ISSUE THREAD

**Issue by Noitidart** [kcrawford/dockutil#37]
This is a really cool project you have. I was wondering is it possible to access dock icons that are not "Kept in Dock" (persisted)? I have an issue:

I created a `desk.app` on my Desktop. This desk.app runs a shell script to launch another application (Firefox). I have "kept in dock" this desk.app

So now click it launches Firefox, and all Firefox is icons all take the icon of `desk.app`, like window dialogs, and miniaturized windows. HOWEVER if I restart Firefox, it leaves my `desk.app` dock icon in the persistent section and now Firefox's actual logo pops up and is over in the non-persistent app section. I'm trying to remove that logo from non-persistent section and associate the Firefox application windows back to the `desk.app` icon I have persisting.

Can you please share your awesome wisdom on this subject on how I can fix this, programtically (as I do this from my firefox addon)

**Comment by kcrawford** [comment]
I'm going to close this issue.  Sorry for the delay.  I don't have an answer on this one.
