### ISSUE TITLE
Feature Request --deleteall

### ISSUE THREAD

**Issue by WardsParadox** [kcrawford/dockutil#38]
I think it would be good for some cases if there was a handle for a delete all flag. It would come in handy when you need to enforce a specific dock layout ( my scenario is Online Testing, where we need to have safari and the browser on the dock ). It would help so that we could clear the dock and start from scratch that way we know exactly what the dock is. I realize we can do this with profiles, but sometimes those are not the best case.

**Comment by MoOx** [comment]
```
dockutil --remove all
```

**Comment by WardsParadox** [comment]
Thank you. Didn't see anything documented about that sorry to waste your time.

**Comment by MoOx** [comment]
It's in the help :)

> ...
> usage:     dockutil --remove <dock item label> | all [ plist_location_specification ] [--no-restart]
all
> ...

Note: I am not the maintainer, just a user :)
