### ISSUE TITLE
In OS X 10.10.2, I have to restart the Dock to see changes

### ISSUE THREAD

**Issue by tjluoma** [kcrawford/dockutil#39]
For example, I did

	dockutil --add /Applications/TextEdit.app

and the dock was automatically restarted, but TextEdit did not appear. I did `killall Dock` in the Terminal, and when the Dock restarted, TextEdit was there.

If I had to guess, I'd say that this probably has something to do with preferences caching, but I'm not sure.

dockutil v. 2.0.2

**Comment by kcrawford** [comment]
Thanks for reporting the issue.   This was probably fixed in one of the releases since then.  It is working for me now.
