### ISSUE TITLE
What is happening when right click? As it udates dock icon

### ISSUE THREAD

**Issue by Noitidart** [kcrawford/dockutil#40]
When i change my dock icon. If just simply right click and check "keep in dock" or if i say "show in finder" it updates the dock icon to show the new icon.

The icon was changed by replacing the icon inside the .app/Contents/Resources folder then making a dummy folder at .app/Contents/dummy dir

Here's a youtube screencast showing it: https://www.youtube.com/watch?v=LFjjVbIXvbg

We see it also updates on keep in dock: https://www.youtube.com/watch?v=yZtmJVanmbw

Is there some objective-c function that is happening on these actions thats triggering the dock icon update? can you please help me to find that as i would love to do it this way rather then killall dock as that unminimizes all my windows.

thanks very much for your advice

**Comment by kcrawford** [comment]
As far as I know, Apple doesn't have a public API for updating the dock.  I agree that if would be much better to use an API.  You would need to file a feature request with them at https://bugreport.apple.com.
