### ISSUE TITLE
Unable to add chrome correctly

### ISSUE THREAD

**Issue by vertti** [kcrawford/dockutil#41]
Maybe I'm doing something wrong but the following simple command:

```
dockutil --add file:///opt/homebrew-cask/Caskroom/google-chrome/latest/Google%20Chrome.app/ --after Launchpad
```

instead of adding chrome as the third element in the dock, add's a weird globe icon as the second to last icon like this:

![screenshot 2015-04-19 08 08 17](https://cloud.githubusercontent.com/assets/557751/7218230/65d4c1f8-e66b-11e4-8671-0b5a7f472706.png)

**Comment by MoOx** [comment]
why do you use file:// ?
It's look like it trying to load an url :/

**Comment by vertti** [comment]
That's how dockutil show's it in the `dockutil --list`, so I just copied it from the listing.

**Comment by MoOx** [comment]
Just do something like

```
dockutil --add "/Applications/Google Chrome.app"
```

Source: https://github.com/MoOx/setup/blob/master/preferences/_osx_.Dock.prefs

**Comment by kcrawford** [comment]
Yes this is the expected behavior I think if you add the item using a URL style.
