### ISSUE TITLE
Claims default dock is not a valid dock plist

### ISSUE THREAD

**Issue by ktappe** [kcrawford/dockutil#42]
I'm getting these errors:

/System/Library/User Template/English.lproj/Library/Preferences/com.apple.dock.plist does not seem to be a home directory or a dock plist

Well, it certainly _seems_ to be a dock plist.  Why is dockutil refusing to work with the template dock plist?  I'm using the same syntax as the -h help page.   This is in 10.10.3 and dockutil 2.0.2.

The only workaround I can think of is for it to alter the current user's dock and then copy that .plist to the template, changing the owner, group, and permissions.  But I'd prefer not resort to such a kludge.

Thanks for any thoughts!

**Comment by kcrawford** [comment]
There is no default file at /System/Library/User Template/English.lproj/Library/Preferences/com.apple.dock.plist on my 10.10.3 system.  You may need to put one there.  Or if you have one there, make sure you are running dockutil as root.  Or maybe that plist is corrupt or invalid.
sudo plutil -lint  '/System/Library/User Template/English.lproj/Library/Preferences/com.apple.dock.plist'

**Comment by billtridico** [comment]
Also getting the '/System/Library/User Template/English.lproj/Library/Preferences/Library/Preferences/com.apple.dock.plist does not seem to be a home directory or a dock plist' message when attempting to update the template dock (sending the command as root). 

sudo plutil -lint '/System/Library/User Template/English.lproj/Library/Preferences/com.apple.dock.plist' returns '/System/Library/User Template/English.lproj/Library/Preferences/com.apple.dock.plist: OK'

Am I understanding correctly that I should be able to modify the template dock using dockutil 2.0.2. on 10.10.3?

**Comment by brunerd** [comment]
Dock templates move in 10.6 to:
/System/Library/CoreServices/Dock.app/Contents/Resources/*.lproj/default.plist

**Comment by kcrawford** [comment]
Is this still an issue.  I'm not able to reproduce it.

**Comment by d-hanes** [comment]
I had this issue when I was not running docuktil as root. "dockutil --add.." versus "sudo dockutil --add". Once I added a "sudo", everything started working.

**Comment by kcrawford** [comment]
Closing this old inactive issue.
