### ISSUE TITLE
Question: dockutil help --no-restart issue?

### ISSUE THREAD

**Issue by WardsParadox** [kcrawford/dockutil#43]
OS X 10.10.3, dockutil 2.0.2
When working on a script for configuring account docks with outset, I noticed that the --no-restart option is always specified after the users home dir location. I am able to do that on occasion, but mainly it errors out `--no-restart does not seem to be a home directory or a dock plist`
After moving it ahead of the plist location it seemed to fix it. Is this a bug, or is the help just a little different from actual use? The example given for the User Template has this correct, but the usage at the top doesn't.

**Comment by kcrawford** [comment]
You are correct.  The documentation usage was wrong.  The --no-restart should come before the plist.   I fixed the documentation.  Thanks for reporting the issue.
