### ISSUE TITLE
Blank tile

### ISSUE THREAD

**Issue by cannyboy** [kcrawford/dockutil#44]
Something like this:

    defaults write com.apple.dock persistent-apps -array-add '{"tile-type"="spacer-tile";}'

Adds a spacer to the dock. Perhaps dockutil can support this.

**Comment by b419kid** [comment]
Sorry for duplicate. I guess it's not something you are interested in implementing?

**Comment by kcrawford** [comment]
It seems reasonable and easy to implement.  I plan to add it if someone else doesn't do it first.

Kyle

**Comment by b419kid** [comment]
Cool. Thanks Kyle 👍

**Comment by kcrawford** [comment]
This is implemented in master and will be part of the the next release.

`dockutil --add '' --type spacer --section apps --after Safari`
