### ISSUE TITLE
automatic is an unsupported --view argument

### ISSUE THREAD

**Issue by brownmike** [kcrawford/dockutil#46]
`dockutil --add ~/Documents --view automatic` results in an error

    Error processing options: unsupported --view argument

But the help page indicates `automatic` is a valid argument for `--view`

    folder_options:
      --view [grid|fan|list|automatic]                              stack view option
      --display [folder|stack]                                      how to display a folder's icon
      --sort [name|dateadded|datemodified|datecreated|kind]         sets sorting option for a folder view

**Comment by lgrimm** [comment]
dockutil --add ~/Documents --view --automatic  does not result in an error

**Comment by brownmike** [comment]
I still get the same error with `--automatic`

It's worth noting that I don't get any errors with any of the other folder view options of `grid`, `fan` or `list`

**Comment by lgrimm** [comment]
Hmm, I'll admit I may be using an older version and if it is a bug, it may have been introduced somewhere along the line. Curious, what version are you using?

**Comment by brownmike** [comment]
$ dockutil --version
    2.0.2

**Comment by lgrimm** [comment]
on my home computer running 2.0.0 the command executes without error, but no documents folder added to dock. I upgraded to v 2.0.2 and got the same error as you. Now I have to check my work mac were I ran it this morning without error and with success...

**Comment by lgrimm** [comment]
Sheez, just checked and at work I still have 1.1.4! (had to downgrade for early 10.10 support I seem to recall.) So you seem to have identified a bug.

**Comment by lgrimm** [comment]
try
dockutil --add ~/Documents --view auto

I had a look at the code and the issue is on line 195:

        elif opt == '--view':
            if arg == 'fan':
                showas = 1
            elif arg == 'grid':
                showas = 2
            elif arg == 'list':
                showas = 3
195=>            elif arg == 'auto':

as a test i edited the line... changing from "auto" to "automatic" and it works as the notes suggest.

to make it work without edits just use "--view auto"

**Comment by brownmike** [comment]
Ah, good find. `auto` is probably a better keyword anyway (shorter), so maybe I can submit a pull request with updated documentation to resolve this. Thanks!

**Comment by lgrimm** [comment]
You're most welcome! It was a good dig, someday we'll find an undiscovered race of humans in all this code:-)
