### ISSUE TITLE
Homebrew installation fails

### ISSUE THREAD

**Issue by mpetersen** [kcrawford/dockutil#48]
Not sure if this is the right place to report, but do you know who maintains the brew formula? On my machine it fails with:

    ==> Downloading https://github.com/kcrawford/dockutil/archive/2.0.2.tar.gz
    Already downloaded: /Library/Caches/Homebrew/dockutil-2.0.2.tar.gz
    ==> Downloading https://pypi.python.org/packages/source/p/plist/plist-0.2.tar.gz

    curl: (22) The requested URL returned error: 404 Not Found
    Error: Failed to download resource "dockutil--plistlib"
    Download failed: https://pypi.python.org/packages/source/p/plist/plist-0.2.tar.gz

**Comment by Vpr99** [comment]
+1

**Comment by Fab1n** [comment]
+1 please fix

**Comment by kcrawford** [comment]
I do not know who maintains it.

Kyle

**Comment by mpetersen** [comment]
There are actually two pull requests already open at homebrew: https://github.com/Homebrew/homebrew/pull/44614/files and https://github.com/Homebrew/homebrew/pull/44488/files

Until these are merged, you can use the file of the pull request directly:

    brew install https://github.com/keith/homebrew/raw/ks-dockutil/Library/Formula/dockutil.rb
