### ISSUE TITLE
Dockutil not working on all commands

### ISSUE THREAD

**Issue by amyers22** [kcrawford/dockutil#49]
I am working on an Office 2016 installer that also removed Office 2011 apps and using this to remove the dock icons. I am trying to use it as such:
$dockutil --add '/Applications/Microsoft Excel.app' --replacing 'Microsoft Excel' --allhomes --no-restart
$dockutil --add '/Applications/Microsoft Outlook.app' --replacing 'Microsoft Outlook' --allhomes --no-restart
$dockutil --add '/Applications/Microsoft PowerPoint.app' --replacing 'Microsoft PowerPoint'  --allhomes --no-restart
$dockutil --add '/Applications/Microsoft Word.app' --replacing 'Microsoft Word'  --allhomes

It will work on one of the items but not all. It will also not remove any of the old dock icons and just seems to process on one, random most of the time, then continue on with the scripts like everything is fine. Should I add anything else to the script or what?

**Comment by mvught** [comment]
I had the same problem, this fixed it:

# Dock Icons change - for current user and all existing users on this computer
echo "Add/Replace Office dock items"

$dockutil --add '/Applications/Microsoft Word.app' --replacing 'Microsoft Word' --allhomes
/bin/sleep 10
$dockutil --add '/Applications/Microsoft Excel.app' --replacing 'Microsoft Excel' --allhomes
/bin/sleep 10
$dockutil --add '/Applications/Microsoft Outlook.app' --replacing 'Microsoft Outlook' --allhomes
/bin/sleep 10
$dockutil --add '/Applications/Microsoft PowerPoint.app' --replacing 'Microsoft PowerPoint' --allhomes
/bin/sleep 10
$dockutil --add '/Applications/Microsoft OneNote.app' --replacing 'Microsoft OneNote' --allhomes

**Comment by kcrawford** [comment]
That sounds like an issue related to cfprefs.  I'll see what I can do to fix that when I get a chance.

Kyle

**Comment by amyers22** [comment]
@mvught , you are a savior. That worked perfect.
