### ISSUE TITLE
Can't add Office 2016 item and keep Office 2011 items

### ISSUE THREAD

**Issue by PEM8000** [kcrawford/dockutil#52]
My users Dock already contains aliases to Office 2011 applications (installed in /Applications/Microsoft Office  2011/). I would like to add aliases from Office 2016 (like /Applications/Microsoft Excel.app) and I can't make it work
Using

> `/usr/local/bin/dockutil --add /Applications/Microsoft\ Excel.app --after 'Microsoft Excel'`

returns 

> `Microsoft Excel already exists in dock. Use --replacing 'Microsoft Excel' to update an existing item`

since both items may share the same name in their Info.plist files.

Replacing the old version by the new one, but I would like to show both versions in the user's Dock.
Would there be a way to check the path of a Dock item in addition to its label ?

**Comment by Macdeviant** [comment]
I'm not a developer but:
What about adding 2016?
`/usr/local/bin/dockutil --add /Applications/Microsoft\ Excel.app --after 'Microsoft Excel 2016'`

**Comment by kcrawford** [comment]
You could try the --label option to give the item you are adding a different name.  I'm not sure if that will work but it is worth a try.

Kyle

**Comment by PEM8000** [comment]
I'll have to thank kcrawford here, this just worked:
> `/usr/local/bin/dockutil --add /Applications/Microsoft\ Excel.app --label 'Microsoft Office 2016' --after 'Microsoft Excel'`
