### ISSUE TITLE
2.0.3 does not work with User Templates 

### ISSUE THREAD

**Issue by VitosX** [kcrawford/dockutil#55]
Version 2.0.3 crashes when I try to modify dock in User Template folder.
Version 2.0.2 works properly.
I guess _os.stat_ does not like quoted paths.

> Traceback (most recent call last):
>   File "/usr/local/bin/dockutil", line 678, in <module>
>     main()
>   File "/usr/local/bin/dockutil", line 269, in main
>     if os.stat(plist_path).st_uid == os.stat('/dev/console').st_uid:
> OSError: [Errno 2] No such file or directory: "'/System/Library/User Template/Non_localized/Library/Preferences/com.apple.dock.plist'"

**Comment by kcrawford** [comment]
Thanks for reporting the issue.

I'll look into it as soon as I can.

Kyle

**Comment by VitosX** [comment]
I fixed it... by disabling some odd code which I don't see any reason for in the first place - quoting plist_path with _pipes.quote_ and then reversing that action by using a little hacky _path_as_string_.

All my test cases work as they should, so is this all quoting game necessary?

**Comment by Dragao75** [comment]
I also have problems with the User Templates.

The error I am receiving: 
dockutil --add /Applications/Firefox.app --no-restart '/System/Library/User Template/English.lproj'
/System/Library/User Template/English.lproj/Library/Preferences/com.apple.dock.plist does not seem to be a home directory or a dock plist

**Comment by VitosX** [comment]
You need root permissions to do that. Use sudo command. But dockutil will crash then unless you use 2.0.2 (or fixed version from my repo).

**Comment by Dragao75** [comment]
I did use root.. (sorry for not including the hash :P ) 
Where do I find your repo ?

**Comment by VitosX** [comment]
Ah, indeed. You need to create some critical keys in com.apple.dock first, or just copy a existing file as template from some user account.

[Here's my fixed version](https://github.com/VitosX/dockutil/blob/master/scripts/dockutil). I hope Kyle will fix his script though (or pull my commits). ;)

**Comment by kcrawford** [comment]
Yes sorry for the delays. I skimmed the changes today.

I want to look at it a little more because I am guessing I have that weird code in there for a reason unless I was just an idiot.

Also didn't understand the reason for the change for mktemp.

Thanks for your help!

Kyle

**Comment by VitosX** [comment]
Maybe quoting code was something needed in older versions? Just take your time.

As for mktemp in your implementation temporary is placed depending on TMPDIR variable, which in some
