### ISSUE TITLE
dock spacers

### ISSUE THREAD

**Issue by b419kid** [kcrawford/dockutil#59]
This is definitely a feature request and not an issue. Is it possible to incorporate spaces into dockutil? 

Example: "defaults write com.apple.dock persistent-apps -array-add '{tile-data={}; tile-type="spacer-tile";}'" <---- adds a transparent moveable icon to create spaces in dock. 

<img width="477" alt="dock spaces" src="https://cloud.githubusercontent.com/assets/2560432/16896904/bd575804-4b6f-11e6-809b-d0864fde3ddb.png">

**Comment by kcrawford** [comment]
Thanks for the feature request.  This has also been requested before.
#44

**Comment by kcrawford** [comment]
This is implemented in master and will be part of the the next release.

`dockutil --add '' --type spacer --section apps --after Safari`

**Comment by b419kid** [comment]
Thank you very much!
