### ISSUE TITLE
Stand Users and Virtual Machines

### ISSUE THREAD

**Issue by gskibum** [kcrawford/dockutil#61]
I just stumbled into an odd bug that you may not have high motivation to fix, but here it is anyway. :-)

I can't get dockutil to work with Standard Users and virtual machines (I use Parallels). Commands that work again and again with admin users fail with standard users.

I get the feedback:

Script result: afp://Server_Name/Archives already exists in dock. Use --replacing 'afp://Server_Name/Archives' to update an existing item
item afp://Server_Name/Archives was not added to Dock

dockutil works with standard users on real hardware. It works with admin users on both virtual machines and real hardware, but it doesn't work with standard users in Parallels virtual machines, which is how I do much of my testing.

**Comment by gskibum** [comment]
An interesting observation I had over the weekend. I was having the same issue with a particular user account on an iMac. Other user accounts would work, but this particular account did the same thing as the virtual machine above (regardless of it being an admin or standard user account).

It turned out to be corrupt ACLs in the user account. Before me IT would "recycle" user accounts when reassigning devices, instead of creating new user accounts. After I corrected the ACLs in this account dockutil started to work properly.

It was just odd that these two different things resulted in tripping up dockutil in the same way.

**Comment by kcrawford** [comment]
Apologies I was not able to respond at the time.  As this is a very old issue I will close it.  Please retest with latest dockutil and report back if you are still having the issue.
