### ISSUE TITLE
Issues in 10.12 Sierra

### ISSUE THREAD

**Issue by vikram731** [kcrawford/dockutil#62]
Hi,
dockutil fails to remove dock icons in OSX 10.12 Sierra.

**Comment by grahamgilbert** [comment]
+1 on this. It fails to add items too. No error messages produced.

**Comment by clburlison** [comment]
For extra data, I'm also unable to get `dockutil` to add or remove icons to the dock this is while a user is logged in. Reproducible at the command line with:

```bash
/usr/local/bin/dockutil --remove all --no-restart
```
or

```bash
/usr/local/bin/dockutil --add '/Applications/Google Chrome.app' --no-restart
```

**Comment by grahamgilbert** [comment]
However, this does work...

```
~ ❯ launchctl unload /System/Library/LaunchAgents/com.apple.Dock.plist
~ ❯ dockutil --add '/Applications/TextEdit.app'
~ ❯ launchctl load /System/Library/LaunchAgents/com.apple.Dock.plist
~ ❯ launchctl start com.apple.Dock.agent
```

**Comment by vikram731** [comment]
After some investigation, I found that killing the dock with HUP signal does not work. Following command fails in 10.12
killall  -HUP Dock

However, sending default SIGTERM does work. 
killall  Dock

**Comment by gregneagle** [comment]
Better to use launchctl to load and unload so that you make your changes while the Dock is not running.

**Comment by kcrawford** [comment]
I like the idea of using launchctl, but for now I'll remove the HUP to get functionality back.

Thanks everyone. 

Kyle

**Comment by gregneagle** [comment]
Feel free to steal anything from here:
https://gist.github.com/gregneagle/5c422d709c93615341a21009f800222e

**Comment by kcrawford** [comment]
Thanks Greg!  That is a beautiful implementation and I will will certainly  steal from it when I have time!

Kyle
