### ISSUE TITLE
no dock restart on 10.12.3

### ISSUE THREAD

**Issue by henningkessler** [kcrawford/dockutil#66]
hi there,

version 2.0.5 does not restart the Dock for me on 10.12.3. I am using this command for example:
`/usr/local/bin/dockutil --add afp://server.fqdn.tld/scans --label scans --replacing scans`

**Comment by AudizineRS4** [comment]
We were having the same issue but figure it out a few minutes ago. What we are using right now. 

#!/bin/sh

#Add Default Apps to Dock “Faculty”
  /usr/local/bin/dockutil --add /Applications/Siri.app --allhomes
  /usr/local/bin/dockutil --add /Applications/Launchpad.app --allhomes
  /usr/local/bin/dockutil --add /Applications/App\ Store.app --allhomes
  /usr/local/bin/dockutil --add /Applications/iBooks.app --allhomes
  /usr/local/bin/dockutil --add /Applications/"iBooks Author.app" --allhomes
  /usr/local/bin/dockutil --add /Applications/iTunes.app --allhomes
  /usr/local/bin/dockutil --add /Applications/Photos.app --allhomes
  /usr/local/bin/dockutil --add /Applications/Preview.app --allhomes
  /usr/local/bin/dockutil --add /Applications/"Photo Booth.app" --allhomes
  /usr/local/bin/dockutil --add /Applications/iMovie.app --allhomes
  /usr/local/bin/dockutil --add /Applications/GarageBand.app --allhomes
  /usr/local/bin/dockutil --add /Applications/Safari.app --allhomes
  /usr/local/bin/dockutil --add /Applications/Firefox.app --allhomes
  /usr/local/bin/dockutil --add /Applications/"Google Chrome.app" --allhomes
  /usr/local/bin/dockutil --add /Applications/Mail.app --allhomes
  /usr/local/bin/dockutil --add /Applications/"Microsoft Outlook.app" --allhomes
  /usr/local/bin/dockutil --add /Applications/Notes.app --allhomes
  /usr/local/bin/dockutil --add /Applications/"Microsoft OneNote.app" --allhomes
  /usr/local/bin/dockutil --add /Applications/"Microsoft Word.app" --allhomes
  /usr/local/bin/dockutil --add /Applications/Pages.app --allhomes
  /usr/local/bin/dockutil --add /Applications/"Microsoft Excel.app" --allhomes
  /usr/local/bin/dockutil --add /Applications/Numbers.app --allhomes
  /usr/local/bin/dockutil --add /Applications/"Microsoft PowerPoint.app" --allhomes
  /usr/local/bin/dockutil --add /Applications/Keynote.app --allhomes
  /usr/local/bin/dockutil --add /Applications/Stickies.app --allhomes
  /usr/local/bin/dockutil --add '~/Documents' --allhomes
  /usr/local/bin/dockutil --add '~/Downloads' --allhomes




#Remove Default Apps to Dock “Faculty”
  /usr/local/bin/dockutil --remove 'System Preferences' --allhomes
  /usr/local/bin/dockutil --remove 'Contacts' --allhomes
  /usr/local/bin/dockutil --remove 'FaceTime' --allhomes
  /usr/local/bin/dockutil --remove 'Messages' --allhomes
  /usr/local/bin/dockutil --remove 'Maps' --allhomes
  /usr/local/bin/dockutil --remove 'Reminders' --allhomes




#Resets the preferences and dock to display the new dock settings”
killall cfprefsd
killall Dock

**Comment by kcrawford** [comment]
I can't reproduce this.

Using your command works and restarts the dock for me on 10.12.3.

What context are you running it from?

root? LaunchAgent? LoginHook?

Kyle

**Comment by AudizineRS4** [comment]
Are you using dockutil 2.0.5?

**Comment by AudizineRS4** [comment]
Nothing special.  One policy with dockutil 2.0.5 and the script.

**Comment by erikng** [comment]
I can't reproduce this either. Dockutil is working fine on 10.12.2/3/4.

Thanks,
Erik Gomez
________________________________

**Comment by AudizineRS4** [comment]
Figured out our script apparently wanted the full path to dockutil

**Comment by henningkessler** [comment]
Hi, sorry for being so late with my respond. I was kinda offline for the last two days ;-)

I was running this command on 10.12.3 with dockutil version 2.0.5 in terminal as that specific user and via outset in the context of a LaunchAgent

Henning

**Comment by henningkessler** [comment]
mmmh this is strange. I found two different versions of dockutil with the same version number 2.0.5. One is restarting the dock the other doesn't. In guess I have to reinstall dockutil ;-).
