### ISSUE TITLE
dockutil --add issue in Sierra 10.12.6

### ISSUE THREAD

**Issue by chrisr2003** [kcrawford/dockutil#70]
I might be missing something simple, but I can't get this to work at all! I removed some items with no problem.  Adding will not happen, tried --allhomes and /Users/$3 , etc.

`sudo dockutil --add /Applications/TextEdit.app`
`Password:`
`Traceback (most recent call last):`
`File "/usr/local/bin/dockutil", line 686, in <module>`
`main()`
`File "/usr/local/bin/dockutil", line 386, in main`
`if addItem(pl, real_add_path, replace_label, position, before_item, after_item, section, displayas, showas, arrangement, tile_type, label_name):`
`File "/usr/local/bin/dockutil", line 547, in addItem`
` label_name = label_name.decode('utf-8')`
`AttributeError: 'NoneType' object has no attribute 'decode'`

**Comment by kcrawford** [comment]
Are you using a released version or the latest version on github?

I ask because I recently merged code that may have triggered the issue but it is not in a release.

Kyle

**Comment by chrisr2003** [comment]
the pkg I built is version 2.0.5 from a git clone.  I'll take a look to see if I can find the release.  Thanks for the reply!
