### ISSUE TITLE
Dockutil is resetting dock several times when used with Casper 10.1.1

### ISSUE THREAD

**Issue by cattleman1** [kcrawford/dockutil#74]
First, let me say that this is an awesome utility.  I have used it for a few years now and everything was working great.

We recently upgraded to Casper 10.1.1 and although I know that Dockutil is not associated with Casper, maybe I could pick someone's brain about this.

I have a script that has minor changes per building that it is used in.  When the system used to start you wouldn't even know that Dockutil was running, the correct Dock was just there ready to use.
With the upgrade, after logging in the Dock gets wiped to a smaller dock and then gets wiped again to the correct dock.  So the screen flashes two times.  Also, I have it so that Casper caches the script and is used Ongoing, for every login.

Does anyone have a clue what I might be doing wrong or what may have happened?  I am including a copy of one of my scripts to this message for reference.  Thank you all for taking a look at this for me.  Have a very great day today!

#!/bin/sh

LoggedInUser=$(python -c 'from SystemConfiguration import SCDynamicStoreCopyConsoleUser; import sys; username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]; username = [username,""][username in [u"loginwindow", None, u""]]; sys.stdout.write(username + "\n");')
LoggedInUserHome="/Users/$LoggedInUser"

configureDefaultDock() {

echo "Logged in user is $LoggedInUser"
echo "Logged in user's home $LoggedInUserHome"

if [ -e /usr/local/bin/dockutil ];
then
   dockutilVersion=`/usr/local/bin/dockutil --version --version`; echo "dockutil version: $dockutilVersion"

/usr/local/bin/dockutil --remove all "$LoggedInUserHome"

/usr/local/bin/dockutil --add '/Applications/Safari.app' --no-restart --position 1 "$LoggedInUserHome"
/usr/local/bin/dockutil --add '/Applications/Firefox.app' --no-restart --position 2 "$LoggedInUserHome"
/usr/local/bin/dockutil --add '/Applications/Google Chrome.app' --no-restart --position 3 "$LoggedInUserHome"
/usr/local/bin/dockutil --add '/Applications/Adobe Photoshop CC 2017/Adobe Photoshop CC 2017.app' --no-restart --position 4 "$LoggedInUserHome"
/usr/local/bin/dockutil --add '/Applications/Adobe Bridge CC 2017/Adobe Bridge CC 2017.app' --no-restart --position 5 "$LoggedInUserHome"
/usr/local/bin/dockutil --add '/Applications/Adobe Lightroom/Adobe Lightroom.app' --no-restart --position 6 "$LoggedInUserHome"
/usr/local/bin/dockutil --add '/Applications/Adobe InDesign CC 2017/Adobe InDesign CC 2017.app' --no-restart --position 7 "$LoggedInUserHome"
/usr/local/bin/dockutil --add '/Applications/Adobe Illustrator CC 2017/Adobe Illustrator.app' --no-restart --position 8 "$LoggedInUserHome"
/usr/local/bin/dockutil --add '/Applications/Adobe Dreamweaver CC 2017/Adobe Dreamweaver CC 2017.app' --no-restart --position 9 "$LoggedInUserHome"
/usr/local/bin/dockutil --add '/Applications/Adobe Acrobat DC/Adobe Acrobat.app' --no-restart --position 10 "$LoggedInUserHome"
/usr/local/bin/dockutil --add '/Applications/MAXON/CINEMA 4D R18/CINEMA 4D.app' --no-restart --position 11 "$LoggedInUserHome"
/usr/local/bin/dockutil --add '/Applications/Unity/Unity.app' --no-restart --position 12 "$LoggedInUserHome"
/usr/local/bin/dockutil --add '/Applications/Autodesk/maya2017/Maya.app' --no-restart --position 13 "$LoggedInUserHome"
/usr/local/bin/dockutil --add '/Applications/Adobe Premiere Pro CC 2017/Adobe Premiere Pro CC 2017.app' --no-restart --position 14 "$LoggedInUserHome"
/usr/local/bin/dockutil --add '/Applications/Avid Media Composer/AvidMediaComposer.app' --no-restart --position 15 "$LoggedInUserHome"
/usr/local/bin/dockutil --add '/Applications/Adobe After Effects CC 2017/Adobe After Effects CC 2017.app' --no-restart --position 16 "$LoggedInUserHome"
/usr/local/bin/dockutil --add '/Applications/Microsoft Word.app' --no-restart --position 17 "$LoggedInUserHome"
/usr/local/bin/dockutil --add '/Applications/Self Service.app' --no-restart --position 18 "$LoggedInUserHome"
/usr/local/bin/dockutil --add '/Applications/System Preferences.app' --no-restart --position 19 "$LoggedInUserHome"

/usr/local/bin/dockutil --add '~/Documents' --no-restart "$LoggedInUserHome"
/usr/local/bin/dockutil --add '~/Downloads' --no-restart "$LoggedInUserHome"
/usr/local/bin/dockutil --add '/Library/Servers/ServersMetro' --view fan --display folder --no-restart "$LoggedInUserHome"

touch $LoggedInUserHome/Library/Preferences/com.company.docksetup.plist

else
   echo "dockutil not installed, skipping initial dock setup..."
fi

}

configureDefaultDock
killall -KILL Dock

exit 0

**Comment by kcrawford** [comment]
Apologies I was not able to respond at the time.  As this is a very old issue I will close it.  Please retest with latest dockutil and report back if you are still having the issue.
