### ISSUE TITLE
Dock set correctly but cannot be changed by User

### ISSUE THREAD

**Issue by HendersonD2** [kcrawford/dockutil#77]
Dockutil 2.0.5 under High Sierra. Running Dockutil using script in Jamf. The dock is set correctly but the end user cannot change it. The end user can drag items off the Dock and add items fine. A log off and back on and the Dock is once again set to the default Dock setup using Dockutil

**Comment by vasquesbc** [comment]
i suppose the script is running as root or other user so it changes the owner of the dock .plist.
i use:

sudo -u USERNAME dockutil ...

to prevent that.

regards,
chris

**Comment by HendersonD2** [comment]
This was my goof. I had another Dockutil script also running that put an item in the Dock everytime. This script was written incorrectly. Once I fixed it, problem solved
