### ISSUE TITLE
Cannot connect directly to Shares via afp or smb

### ISSUE THREAD

**Issue by kgirnz** [kcrawford/dockutil#78]
Well...kind of.

using:
dockutil --add "afp://servername/servershare" will no longer work. You will be prompted each time with login credentials and it will not connect directly to the share. Rather it will show all shares available from server side.

This has never been an issue until apple release an update last week. Hoping to see if anything can be sorted from the dockutil side.

Note this happens on Sierra up to the latest Mojave release.

**Comment by firwooduk** [comment]
I'm also having this issue with Macs across multiple sites.  Is this something thats likely to be fixed soon?

**Comment by kcrawford** [comment]
This is an Apple bug.  It is expected to be fixed in 10.14.3 but they won’t say about 10.13.

Kyle

**Comment by kgirnz** [comment]
Perfect. Thanks for the update.

**Comment by kcrawford** [comment]
Closing this issue as I don't think it is a dockutil issue.
