### ISSUE TITLE
Mojave compatibility

### ISSUE THREAD

**Issue by mistacabbage** [kcrawford/dockutil#80]
Is dockutil compatible with macOS 10.14 Mojave?

**Comment by Jorsta** [comment]
Great tool btw!

**Comment by damacguy** [comment]
It doesn't support 10.14's ability to hide/show Recent Applications in the Dock. Not a make/break feature, but it'd still be nice to have.

**Comment by Gerst20051** [comment]
I can confirm that something is broke with macOS Catalina.

**Comment by kcrawford** [comment]
With the 3.0 release, dockutil is supported on Big Sur and Monterey.  It may also work on Catalina.  Older OS versions should use dockutil 2.x but won't get further development.
