### ISSUE TITLE
Issue with user folders

### ISSUE THREAD

**Issue by kylejericson** [kcrawford/dockutil#82]
I used this tool to add the users downloads folder to the dock. The issue I have is the icon is a question mark. If I right click this and change the view as Stack and then back to view as folder the icon works. I posted my script in Jamf Nation. 
The item seems to work without issue beside the icon not being set right.
OS: 10.14.4 
dockutil: 2.0.5

[Jamf Nation](https://www.jamf.com/jamf-nation/discussions/31760/dockutil-on-10-14#responseChild183516)

**Comment by kcrawford** [comment]
I get the icon if the folder exists and a question mark if it doesn’t.

If I create the missing folder then restart the Dock the icon corrects itself.

What is triggering/running the script?

Are you sure the Downloads directory exists when the script is run?

Kyle

**Comment by kylejericson** [comment]
I attached the full script from the Jamf Nation. Also verified the folder is present.

**Comment by kylejericson** [comment]
I added the --no-restart and it seemed to fix my issue.
