### ISSUE TITLE
GUID should be (64-bit) integer

### ISSUE THREAD

**Issue by chris0e3** [kcrawford/dockutil#83]
Hello,
I’ve looked as com.apple.dock.plist files from OSX 10.8, 10.12 & 10.14.  In all cases the `GUID` properties are always integers (and not UUIDs).
I have tried `<key>GUID</key><integer>$(date "+$RANDOM$$%s")</integer>` in a Bash script that adds an app and that seems to work correctly.

I don’t believe that your `<key>GUID</key><string>$(uuidgen)</string>` equivalent is correct - you’ve just been lucky :-).

Hope this helps.

**Comment by Gerst20051** [comment]
I ran this command to see what the GUIDs are for me:

`plutil -convert xml1 ~/Library/Preferences/com.apple.dock.plist -o - | grep GUID -n1 | grep integer`

This is the output:

```
<integer>3994904625</integer>
<integer>3994904626</integer>
<integer>3994904627</integer>
<integer>3994904628</integer>
<integer>3994904629</integer>
<integer>3994904630</integer>
<integer>3994904631</integer>
<integer>3994904632</integer>
<integer>3994904633</integer>
<integer>3994904634</integer>
<integer>3994904635</integer>
<integer>3994904636</integer>
<integer>3994904637</integer>
```

Like you mentioned `/usr/bin/uuidgen` is what `dockutil` seems to be using:

https://github.com/kcrawford/dockutil/blob/b2900281ba51575d1cda7f6905382e89df5d286d/scripts/dockutil#L583

https://github.com/kcrawford/dockutil/blob/b2900281ba51575d1cda7f6905382e89df5d286d/scripts/dockutil#L538

Perhaps this is why it's failing to add new items to the dock in macOS Catalina?

https://github.com/kcrawford/dockutil/issues/84

**Comment by kcrawford** [comment]
This is resolved in dockutil 3.  Thanks for reporting the issue.
