### ISSUE TITLE
Would you please make a new release with the latest script?

### ISSUE THREAD

**Issue by manlao** [kcrawford/dockutil#85]
Hi, @kcrawford 

I would like to install dockutil through homebrew.
But the formula is using the latest released script, which is version 2.0.5 released in 2016.

So would you please make a new release? Then someone can update the formula with the new release.

Version 2.0.5 still seems to have some problem to work with unicode characters.

Thank you so much

**Comment by Gerst20051** [comment]
The problem is that there haven't been many updates since that version.

https://github.com/kcrawford/dockutil/compare/2.0.5...master

**Comment by zachheine** [comment]
+1

**Comment by trwalzer** [comment]
Any chance of this happening?

**Comment by Gerst20051** [comment]
You can now grab the latest version with this cask! 🥳 🎉 🚀

https://github.com/kcrawford/dockutil/issues/127

https://github.com/hpedrorodrigues/homebrew-tools/blob/master/Casks/dockutil.rb

**Comment by kcrawford** [comment]
Closing this old inactive issue.  Also just created a release.
