### ISSUE TITLE
Catalina Question Marks

### ISSUE THREAD

**Issue by Maddog1314** [kcrawford/dockutil#86]
Kyle,

I just tested dockutil 2.0.5 in a Mac with a freshly installed version Catalina from Apple. I've been using dockutil successfully for a couple of years now in our Jamf Server. In the last two tests  I received "?" marks in the Dock instead of the Applications that all come from the /Applications folder. Utilities and everything else shows as expected. Is this a known issue or am I just doing something incorrectly? Thanks for all the work you do!

**Comment by kcrawford** [comment]
I’m not seeing that issue but maybe usage specific.

Kyle

**Comment by kevindigg** [comment]
Are you trying to use your existing dockutil scripts? We had this issue and it turns out the problem is that in Catalina many of the applications now reside in /System/Applications/. In our standard dock setup the only apps that worked as before were /Applications/Safari and /Applications/Self Service

**Comment by Maddog1314** [comment]
I'm trying to put in Applications directly from the /Applications folder
like Dictionary or Automater and they show up as a "?" only. The strange
thing is that other items that I have developed and put into the
Applications folder or items from /System/Library/CoreServices/Applications
show up there. It looks like in Get Info. they still all have the same .app
after the Application name.

Jeff Madson
IT Engineer 3
jeffrey.madson@lsccom.com <sara.k.zachman@lsccom.com>
D: 920.903.5842
[image: lsccom.com]
LSC Communications
655 Brighton Beach Rd.
Menasha, WI 54952
United States
lsccom.com

**Comment by erikng** [comment]
You have to update your scripts for Catalina. While the paths are identical in "Finder" behind the scenes they have moved to /System/Applications with the exception of Safari.

Thanks,
Erik Gomez
________________________________

**Comment by Maddog1314** [comment]
Thanks Erik and Everyone,

Putting in the new paths fixed the problem.

Jeff Madson
IT Engineer 3
jeffrey.madson@lsccom.com <sara.k.zachman@lsccom.com>
D: 920.903.5842
[image: lsccom.com]
LSC Communications
655 Brighton Beach Rd.
Menasha, WI 54952
United States
lsccom.com

**Comment by kcrawford** [comment]
3.0.1 will use path from /System/Applications if it exists and the /Applications path does not exist

**Comment by Maddog1314** [comment]
Kyle,

Very cool, thanks!

Jeff Madson
IT Engineer 3
***@***.***
D: 920.915.8619
[image: lsccom.com]
LSC Communications
655 Brighton Beach Rd.
Menasha, WI 54952
United States
lsccom.com
