### ISSUE TITLE
Notes.app shows up as ? when added through dockutil

### ISSUE THREAD

**Issue by non-binary** [kcrawford/dockutil#89]
Hi there! First just wanted to say that I love this tool and you've done an amazing job with it.

For some reason, when I add the Notes.app to the dock through dockutil it shows up as missing. I have to manually remove the question mark and add Notes in its place. This is of course not ideal.

<img width="837" alt="Screen Shot 2020-01-02 at 11 55 04 AM" src="https://user-images.githubusercontent.com/6799989/71684004-1aece880-2d62-11ea-9f5e-cf13aba8b151.png">

I'm adding Notes using dockutil as so:

```
dockutil --add /Applications/Notes.app
```

Any ideas? Thanks and happy new years!

**Comment by dannyhanes** [comment]
Try this. 

`dockutil --add "/System/Applications/Notes.app"`

Apple applications are starting to move to `/System/Applications` instead of leaving them in `/Applications`

**Comment by non-binary** [comment]
That worked! Thanks for the assistance! (I am on Catalina)
