### ISSUE TITLE
Alias for .apps fail to add to dock

### ISSUE THREAD

**Issue by K1jaff** [kcrawford/dockutil#90]
Pretty sure i mean Alias here but correct me if i'm worng, .app is "re-labelled" to a friendly name, this fails to add via this alias, when you drag the app to terminal it shows the actual name of the .app.

UI methods of adding to the dock retain the friendly alias name.

**Comment by kcrawford** [comment]
It has been a long time.  Sorry for not replying at the time this was opened.  I must have been busy at the time.

In my testing in dockutil 3, adding an alias keeps the alias name.
