### ISSUE TITLE
Best practice for adding a list of items to dock?

### ISSUE THREAD

**Issue by bryand23** [kcrawford/dockutil#92]
I've got a bash script with an array of application paths that I'm using to create standardized docks, and I've found that you can't simply iterate through a list adding each item to the dock. It takes a few seconds for the dock to refresh and somewhere in the process it ends up skipping over several items in the list.

I'm working around this at the moment by adding `sleep 5` but I was wondering if there was a better way to accomplish this? Or perhaps a way to pass an array to dockutil to add multiple items to the dock at once?

**Comment by erikng** [comment]
I do it with a python wrapper

It's worked pretty well for me for several years now.

https://github.com/erikng/installapplicationsdemo/blob/master/installapplications/scripts/user/dockutil.py

Thanks,
Erik Gomez
________________________________

**Comment by bryand23** [comment]
Oh, small world @erikng!  I was just playing around with your UMAD program the other day :)

It looks like the --no-restart flag is the fix to my issue, if an item is being added to the dock during the restart, it has a pretty good chance of not ending up in the dock.

Thanks!
