### ISSUE TITLE
Support utf8 label

### ISSUE THREAD

**Issue by resyst-it** [kcrawford/dockutil#96]
Hello,

It is possible to support utf8 label ?
Ex : dockutil --add "/System/Applications/System Preferences.app" --label "Préférences Système"

The only thing to add an utf8 label i add this two lines : 
```
reload(sys)
sys.setdefaultencoding('utf-8')
```

Thank you

**Comment by kcrawford** [comment]
This seems to be working properly in dockutil 3.  Please retest in dockutil 3.
