### ISSUE TITLE
Missing Icon line 10

### ISSUE THREAD

**Issue by threedotseven** [kcrawford/dockutil#99]
I'm using dock util 2.0.5 and have worked for me using the script below for all the OS in my environment. Just yesterday  I was working on a laptop with 10.15.6 and noticed it wouldn't add the PowerPoint icon based on the script i'm using below. If I moved the PowerPoint line between Word and Excel, then it would show PowerPoint but  Excel would be left out. I then left line 10 blank and move powerpoint to line 11 and it still would not show. I also tried adding "/System/Applications/TextEdit.app" in line 10 and PowerPoint to line 11, then it would add PowerPoint but not TextEdit. Has anyone experienced this issue and came up with a fix?

#!/bin/bash

# Apply the dockutil settings to current logging in user $3

sudo -u $3 /usr/local/bin/dockutil --remove all "/Users/$3"
sudo -u $3 /usr/local/bin/dockutil --add '/Applications/Self Service.app' "/Users/$3"
sudo -u $3 /usr/local/bin/dockutil --add '/Applications/Google Chrome.app' "/Users/$3"
sudo -u $3 /usr/local/bin/dockutil --add '/Applications/Microsoft Word.app' "/Users/$3"
sudo -u $3 /usr/local/bin/dockutil --add '/Applications/Microsoft Excel.app' "/Users/$3"
sudo -u $3 /usr/local/bin/dockutil --add '/Applications/Microsoft PowerPoint.app' "/Users/$3"
sudo -u $3 /usr/local/bin/dockutil --add '/Applications/VLC.app' "/Users/$3"
sudo -u $3 /usr/local/bin/dockutil --add '/Applications/Google Drive File Stream.app' "/Users/$3"
sudo -u $3 /usr/local/bin/dockutil --add '~/Downloads' --view grid --display folder --sort name "/Users/$3"

**Comment by pretzelmaker** [comment]
A couple of things come to mind for this situation. If possible, you should be working with a clean dock. I have gone as far to do `defaults delete com.apple.dock; killall Dock` prior to utilizing dockutil. In theory this clears out any hiccups that may be present in the dock plist.

Secondly, I have also found that adding the `--no-restart` flag to all dockutil commands prior to the last one helps avoid some of the unexplainable heartburn that can be seen when executing a larger than 1 set of commands.

Give these a shot and see if they help. I am by no means an expert or contributor but I'd be happy to help where possible.

**Comment by kcrawford** [comment]
Yes adding --no-restart as @pretzelmaker suggested is recommended.  Or you can --add multiple times in same line repeating the --add path/to/item.  Closing this issue.
